#Scrap metrics from /actuator/prometheus on regular interval from specified port.
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      # If running Spring Boot in a container, use the container name.
      # If running Spring Boot on your host machine, use 'host.docker.internal'.
      - targets: [ 'host.docker.internal:8081' ]